### ISSUE TITLE
Add proper VeRNAl input format to documentation

### ISSUE THREAD

**Issue by larakollokian** [TeamW-P/API-docs#4]
Currently the input of VeRNAl in our documentation is just a placeholder object.

![image](https://user-images.githubusercontent.com/35381483/105781932-74155480-5f41-11eb-938f-be094e8feffd.png)

We need to add the actual input format with proper descriptions and examples as soon as possible so we can get feedback from our supervisors.

The change needs to happen in `API-docs/VeRNAl/VernalInputSchema.yaml`. Make sure to keep the first line `VernalInput:` intact. This file also refers to the file `API-docs/VeRNAl/VernalSettingsSchema.yaml` to describe the advanced settings parameter, so make sure to change that too.

**Comment by rayanosseiran** [comment]
Done within Postman API
