### ISSUE TITLE
Add proper VeRNAl input format to documentation

### ISSUE THREAD

**Issue by larakollokian** [TeamW-P/API-docs#5]
Currently the output of VeRNAl in our documentation is just a placeholder object.

![image](https://user-images.githubusercontent.com/35381483/105782149-ef770600-5f41-11eb-8109-1b8628d48deb.png)

We need to add the actual output format with proper descriptions and examples as soon as possible so we can get feedback from our supervisors.

The change needs to happen in `API-docs/VeRNAl/VernalOutputSchema.yaml`. Make sure to keep the first line `VernalOutput:` intact.

**Comment by rayanosseiran** [comment]
Done within Postman API!
