### ISSUE TITLE
Add proper RNAmigos output format to documentation

### ISSUE THREAD

**Issue by larakollokian** [TeamW-P/API-docs#6]
Currently the output of RNAmigos in our documentation is just a placeholder object.

![image](https://user-images.githubusercontent.com/35381483/105782358-5f858c00-5f42-11eb-9771-e878c32c98fe.png)

We need to add the actual output format with proper descriptions and examples as soon as possible so we can get feedback from our supervisors.

The change needs to happen in `API-docs/RNAmigos/RnamigosOutputSchema.yaml`. Make sure to keep the first line `RnamigosOutput:` intact.

**Comment by rayanosseiran** [comment]
Done
