### ISSUE TITLE
Add example values and descriptions for all the variables in the documentation

### ISSUE THREAD

**Issue by larakollokian** [TeamW-P/API-docs#7]
Make sure that every variable in the input/output objects in our documentation has proper example values and a good description. This will make the tool easier to understand for future users who are not RNA experts. Most variables already have examples and a good description, but this is to make sure everything is there and makes sense.

For example:
![image](https://user-images.githubusercontent.com/35381483/105782853-3b767a80-5f43-11eb-9a7d-83d2a2685255.png)

We should have variable name, example value, description and even a list of accepted inputs if necessary.

**Comment by rayanosseiran** [comment]
Done within the Postman API
